# Generated by Django 4.2 on 2024-04-02 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_expense_expensegroup_settlement_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensegroup',
            name='group',
        ),
        migrations.AddField(
            model_name='expensegroup',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expensegroup',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expensegroup',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expensegroup',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.expense'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
